# Define the "cinder-volume-nfs-secrets" Secret that contains sensitive
# information pertaining to the [nfs] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-nfs-secrets
type: Opaque
stringData:
  nfs-secrets.conf: |
    [nfs]
    nas_host=192.168.130.1
    nas_share_path=/var/nfs/cinder
