apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
    service: cinder
  name: 99-master-cinder-enable-iscsid
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/iscsi/iscsid.conf
          overwrite: true
          # Mode must be decimal, this is 0600
          mode: 384
          user:
            name: root
          group:
            name: root
          contents:
            # Source can be a http, https, tftp, s3, gs, or data as defined in rfc2397.
            # This is the rfc2397 text/plain string format
            # Change login timeout and retries so total time is not 120 seconds but 15 (3 x 5)
            # This is convenient for testing with failed paths, production env may choose to leave defaults
            source: data:,node.session.initial_login_retry_max%20%3D%203%0Anode.conn%5B0%5D.timeo.login_timeout%20%3D%205%0A
    systemd:
      units:
      - enabled: true
        name: iscsid.service
