# permissions for end users to view cinderapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cinderapi-viewer-role
rules:
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderapis/status
  verbs:
  - get
