# permissions for end users to edit cindervolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cindervolume-editor-role
rules:
- apiGroups:
  - cinder.openstack.org
  resources:
  - cindervolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cinder.openstack.org
  resources:
  - cindervolumes/status
  verbs:
  - get
