# permissions for end users to edit cinderbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cinderbackup-editor-role
rules:
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderbackups/status
  verbs:
  - get
