# permissions for end users to view cinderschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cinderscheduler-viewer-role
rules:
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderschedulers/status
  verbs:
  - get
