# permissions for end users to view cinderbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cinderbackup-viewer-role
rules:
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderbackups/status
  verbs:
  - get
