# permissions for end users to view cindervolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cindervolume-viewer-role
rules:
- apiGroups:
  - cinder.openstack.org
  resources:
  - cindervolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cinder.openstack.org
  resources:
  - cindervolumes/status
  verbs:
  - get
