apiVersion: cinder.openstack.org/v1beta1
kind: Cinder
metadata:
  name: cinder
  namespace: openstack
spec:
  serviceUser: cinder
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: cinder
  rabbitMqClusterName: rabbitmq
  cinderAPI:
    containerImage: quay.io/podified-antelope-centos9/openstack-cinder-api:current-podified
  cinderScheduler:
    containerImage: quay.io/podified-antelope-centos9/openstack-cinder-scheduler:current-podified
  cinderBackup:
    containerImage: quay.io/podified-antelope-centos9/openstack-cinder-backup:current-podified
  secret: cinder-secret
  cinderVolumes:
    volume1:
      containerImage: quay.io/podified-antelope-centos9/openstack-cinder-volume:current-podified
