# To be able to use this sample it is necessary to:
# - Have a NetApp ONTAP backend with NFS support
# - Have the NetApp storage credentials and NFS configuration in cinder-volume-ontap-secrets.yaml
#
# NOTE: Rather than using a shares-config file, the driver uses the nas_host
# and nas_share_path parameters in the secrets file. For multiple shares,
# configure a separate cinder-volume backend and secrets file for each share.

apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  cinder:
    template:
      cinderVolumes:
        ontap-nfs:
          networkAttachments:
          - storage
          customServiceConfig: |
            [ontap]
            volume_backend_name=ontap
            volume_driver=cinder.volume.drivers.netapp.common.NetAppDriver
            nfs_snapshot_support=true
            nas_secure_file_operations=false
            nas_secure_file_permissions=false
            netapp_server_hostname=hostname
            netapp_server_port=80
            netapp_storage_protocol=nfs
            netapp_storage_family=ontap_cluster
          customServiceConfigSecrets:
          - cinder-volume-ontap-secrets
