# Define the "cinder-volume-ontap-secrets" Secret that contains sensitive
# information pertaining to the [ontap] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-ontap-secrets
type: Opaque
stringData:
  ontap-cinder-secrets: |
    [ontap]
    netapp_login=admin_username
    netapp_password=admin_password
    netapp_vserver=svm_name
    nas_host=10.63.165.215
    nas_share_path=/nfs/test
