# Define the "cinder-volume-ontap-secrets" Secret that contains sensitive
# information pertaining to the [iscsi] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-ontap-secrets
type: Opaque
stringData:
  ontap-cinder-secrets.conf: |
    [ontap]
    netapp_login=admin_username
    netapp_password=admin_password
    netapp_vserver=svm_name
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-ontap-shares-secrets
type: Opaque
stringData:
  shares-config: |
    10.63.165.215:/nfs/test
    10.63.165.215:/nfs2/test2
