resources:
  - https://raw.githubusercontent.com/openstack-k8s-operators/openstack-operator/main/config/samples/core_v1beta1_openstackcontrolplane_galera_network_isolation.yaml
patches:
  # Remove existing backends so we don't end up with a volume1 useless object
  - target:
      kind: OpenStackControlPlane
      name: .*
    patch: |-
      - op: remove
        path: /spec/cinder/template/cinderVolumes
  # Rename OpenStackControlPlane to "openstack", so all backend samples can use
  # that name regardless of the name used in the source base.
  - target:
      kind: OpenStackControlPlane
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: openstack
  # Make our base customizations
  - target:
      kind: OpenStackControlPlane
      name: .*
    path: openstack.yaml
