#  Changes to the openstack-operator base YAML
#  Changes:
#  - Disable Manila
#  - Enable debug logs for Cinder
#  - Enable Cinder backup using swift
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  manila:
    enabled: false
  cinder:
    template:
      customServiceConfig: |
        [DEFAULT]
        debug = true
      cinderBackup:
        networkAttachments:
        - storage
        replicas: 1
        customServiceConfig: |
          [DEFAULT]
          backup_driver = cinder.backup.drivers.swift.SwiftBackupDriver
          # Below are defaults, explicit for illustration purposes
          backup_swift_auth = per_user
          keystone_catalog_info = identity:Identity Service:publicURL
          swift_catalog_info = object-store:swift:publicURL
