#  Changes to the openstack-operator base YAML
#  Changes:
#  - Disable Manila
#  - Enable debug logs for Cinder
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  manila:
    enabled: false
  cinder:
    template:
      customServiceConfig: |
        [DEFAULT]
        debug = true
