# Define the "cinder-volume-ontap-secrets" Secret that contains sensitive
# information pertaining to the [ontap] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-ontap-secrets
type: Opaque
stringData:
  ontap-secrets.conf: |
    [ontap]
    netapp_login=admin_username
    netapp_password=admin_password
    netapp_vserver=svm_name
    netapp_server_hostname=hostname
    netapp_server_port=80
