# Define the "cinder-volume-3par-secrets" Secret that contains sensitive
# information pertaining to the [hpe3par] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-3par-secrets
type: Opaque
stringData:
  hpe3par-secrets.conf: |
    [hpe3par]
    hpe3par_api_url=https://10.10.0.141:8080/api/v1
    hpe3par_username=edit3par
    hpe3par_password=3parpass
    hpe3par_cpg=OpenStackCPG_RAID5_NL
    san_ip=10.10.22.241
    san_login=3paradm
    san_password=3parpass
    hpe3par_iscsi_ips=10.10.220.253:3261,10.10.222.234
    hpe3par_cpg_snap=OpenStackSNAP_CPG
