# Define the "cinder-volume-pure-secrets" Secret that contains sensitive
# information pertaining to the [pure] backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-pure-secrets
type: Opaque
stringData:
  pure-secrets.conf: |
    [pure]
    san_ip=192.168.1.32
    pure_api_token=c6033033-fe69-2515-a9e8-966bb7fe4b40
